version: "3"

services:
  postgres:
    image: "postgres:alpine"
    container_name: "postgres"
    restart: "always"
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
  nginx:
    image: "nginx:alpine"
    container_name: "nginx"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - 8080:80
  backend:
    build: "./backend"
    container_name: "backend"
    ports:
      - 3001:3001
    environment:
      - DB_USER=dev
      - DB_PASSWORD=dev
      - DB_DATABASE=dev
      - DB_HOST=postgres
      - JWT_SECRET=secret
      - LOG_LEVEL=debug
      - PORT=3001
    depends_on:
      - postgres
  frontend:
    build: "./frontend"
    container_name: "frontend"
    ports:
      - 3000:3000
    depends_on:
      - backend